import Head from 'next/head';
import type { ReactNode } from 'react';

import Nav from './Nav';

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen bg-base-100 text-base-content">
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="flex flex-col items-center justify-center flex-1 w-full p-2 text-center md:px-20">
        {children}
      </main>
      <footer className="flex items-center justify-center w-full h-24 border-t">
        Powered by{' '}
        <a
          className="pl-1 link-hover link-primary link"
          href="https://github.com/sidefoundation"
        >
          Side Protocol Labs 
        </a>
      </footer>
    </div>
  );
}
