import Head from 'next/head';
import type { ReactNode } from 'react';

import Nav from './Nav';

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <div className="bg-base-100 text-base-content flex min-h-screen flex-col items-center justify-center">
      <Head>
        <title>{process.env.NEXT_PUBLIC_SITE_TITLE}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />
      <main className="flex w-full flex-1 flex-col items-center justify-center p-2 text-center md:px-20">
        {children}
      </main>
      <footer className="flex h-24 w-full items-center justify-center border-t">
        Powered by{' '}
        <a
          className="link-hover link-primary link pl-1"
          href="https://github.com/cosmos/cosmjs"
        >
          CosmJS
        </a>
        <span className="pl-1"> and</span>
        <a
          className="link-hover link-primary link pl-1"
          href="https://keplr.app/"
        >
          Keplr
        </a>
      </footer>
    </div>
  );
}
